### ISSUE TITLE
[feat] 프로젝트 초기 세팅

### ISSUE THREAD

**Issue by kimtaehoonDev** [GymHubCommunity/GymHub-BE#1]
## 🏋🏻 어떤 개발 사항인가요?
프로젝트 초기 세팅을 진행합니다.

##  💪🏻 TODO
- [x] Spring Boot 의존성 추가
- [x] issue, pr 템플릿
- [x] 메인 클래스 이름 **GymHub**BackApplication으로 변경
- [x] application.properties -> yml로 변경
- [x] main 브랜치로 push되지 않도록 설정
- [x]  라벨 커스터마이징
