### ISSUE TITLE
[feat] 운동기구 검색

### ISSUE THREAD

**Issue by kimtaehoonDev** [GymHubCommunity/GymHub-BE#119]
### 🏋🏻 어떤 개발 사항인가요?

BodyCategory[상체,하체,전신]를 사용해 운동 기구를 검색할 수 있게 만듭니다.
모든 운동 기구를 조회할 수 있게 만듭니다.

### 💪🏻 TODO

- [x] 신체 부위 추가하기
- [x] 각 신체부위의 상하체 여부를 구별할 수 있게 만들기
- [x] BodyCategory를 사용한 검색 기능 구현 
- [x] 전체 운동기구 조회 기능 구현
