### ISSUE TITLE
[refactor] 배포 전 자잘한 코드 수정

### ISSUE THREAD

**Issue by JWbase** [GymHubCommunity/GymHub-BE#158]
### 🏋🏻 어떤 리팩토링인가요?

코드 작성하면서 자잘하게 놓친 부분을 리팩토링 합니다.

### 💪🏻 TODO

- [x] 엔티티 BaseTimeEntity 상속
- [x] EqualsAndHashtag에 callSuper = false 명시
- [x] PostResponse에 변수타입(Slice) 제거
