### ISSUE TITLE
[feat] Presigned URL 발급

### ISSUE THREAD

**Issue by kimtaehoonDev** [GymHubCommunity/GymHub-BE#56]
### 🏋🏻 어떤 개발 사항인가요?

서버의 부하를 줄이기 위해 이미지를 저장하는 로직을 클라이언트에게 위임합니다.
이 때, 서버는 클라이언트에게 Presigned URL을 발급해주는 방식으로 보안 이슈를 해결합니다.

추가로 로컬 환경에서 S3 환경을 에뮬레이션하기 위해 LocalStack을 적용합니다.

### 💪🏻 TODO

- [x] LocalStack 설치
- [x] Local 환경에서 PresignedUrl 잘 동작하는지 테스트
- [x] S3, IAM 학습(실제 배포 환경에 적용은 추후..)
- [x] 랜덤한 파일명 생성
