### ISSUE TITLE
[etc] Swagger에 Authorization 헤더 입력창 만들기

### ISSUE THREAD

**Issue by kimtaehoonDev** [GymHubCommunity/GymHub-BE#57]
### 🏋🏻 어떤 이슈인가요?

프론트엔드 개발자들이 Swagger를 통해 인가 작업을 할 수 있게 Authorization 헤더를 입력할 수 있게 만듭니다.

### 💪🏻 TODO

- [x] Swagger Authorization 헤더 입력할 수 있도록 구현
- [x] init.sql 생성해 회원을 둘 저장
- [x] 테스트용 Key로 1달동안 유효한 토큰 생성하기
