### ISSUE TITLE
[etc] 누락된 작업 추가

### ISSUE THREAD

**Issue by kimtaehoonDev** [GymHubCommunity/GymHub-BE#66]
### 🏋🏻 어떤 이슈인가요?

작업하면서 누락된 작업들을 추가합니다.

### 💪🏻 TODO

- [x] data.sql에서 members 테이블에 deleted 컬럼을 추가
- [x] JPQL @Param 빠진 부분 추가
- [x] JpaRepository 메서드에서 값타입 제거
- [x] lombok 라이브러리 jacoco 타겟에서 제거 
- [x] .DS_Store gitignore 처리
